window.MOCK_MENU = {
  "categories": [
    {
      "id": "cat-marmitas",
      "name": "Marmitas",
      "slug": "marmitas",
      "description": "Marmitas P, M e G.",
      "sort_order": 1,
      "active": true
    },
    {
      "id": "cat-porcoes",
      "name": "Porções",
      "slug": "porcoes",
      "description": null,
      "sort_order": 2,
      "active": true
    },
    {
      "id": "cat-executivos",
      "name": "Pratos Executivos",
      "slug": "pratos-executivos",
      "description": "Acompanham arroz, feijão, fritas e farofa.",
      "sort_order": 3,
      "active": true
    },
    {
      "id": "cat-especiais",
      "name": "Pratos Especiais",
      "slug": "pratos-especiais",
      "description": "Acompanham arroz e fritas.",
      "sort_order": 4,
      "active": true
    },
    {
      "id": "cat-massas",
      "name": "Massas",
      "slug": "massas",
      "description": "Acompanham arroz e fritas.",
      "sort_order": 5,
      "active": true
    },
    {
      "id": "cat-refrigerantes",
      "name": "Refrigerantes",
      "slug": "refrigerantes",
      "description": null,
      "sort_order": 6,
      "active": true
    },
    {
      "id": "cat-sucos",
      "name": "Sucos",
      "slug": "sucos",
      "description": null,
      "sort_order": 7,
      "active": true
    },
    {
      "id": "cat-cervejas",
      "name": "Cervejas",
      "slug": "cervejas",
      "description": "Venda proibida para menores de 18 anos.",
      "sort_order": 8,
      "active": true
    },
    {
      "id": "cat-alcool",
      "name": "Bebidas alcoólicas",
      "slug": "bebidas-alcoolicas",
      "description": "Venda proibida para menores de 18 anos.",
      "sort_order": 9,
      "active": true
    }
  ],
  "products": [
    {
      "id": "prod-001",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Isca de tilápia",
      "slug": "isca-de-tilapia-p",
      "size": "P",
      "price": 16.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 1,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-002",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Calabresa acebolada",
      "slug": "calabresa-acebolada-p",
      "size": "P",
      "price": 16.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 2,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-003",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Filé de frango à milanesa",
      "slug": "file-de-frango-a-milanesa-p",
      "size": "P",
      "price": 16.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 3,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-004",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Frango grelhado",
      "slug": "frango-grelhado-p",
      "size": "P",
      "price": null,
      "description": "Preço não informado no arquivo.",
      "image_path": null,
      "active": false,
      "available": true,
      "featured": false,
      "sort_order": 4,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-005",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Linguiça toscana",
      "slug": "linguica-toscana-p",
      "size": "P",
      "price": 16.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 5,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-006",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Bisteca de porco",
      "slug": "bisteca-de-porco-p",
      "size": "P",
      "price": 16.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 6,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-007",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Carne de panela",
      "slug": "carne-de-panela-p",
      "size": "P",
      "price": 16.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 7,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-008",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Strogonoff de frango",
      "slug": "strogonoff-de-frango-p",
      "size": "P",
      "price": null,
      "description": "Preço não informado no arquivo.",
      "image_path": null,
      "active": false,
      "available": true,
      "featured": false,
      "sort_order": 8,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-009",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Carne seca acebolada",
      "slug": "carne-seca-acebolada-p",
      "size": "P",
      "price": 19.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 9,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-010",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Costelinha",
      "slug": "costelinha-p",
      "size": "P",
      "price": 19.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 10,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-011",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Parmegiana de frango",
      "slug": "parmegiana-de-frango-p",
      "size": "P",
      "price": 24.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 11,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-012",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Filé de frango c/ creme de milho",
      "slug": "file-de-frango-creme-de-milho-p",
      "size": "P",
      "price": 24.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 12,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-013",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Feijoada",
      "slug": "feijoada-m",
      "size": "M",
      "price": 24.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 13,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-014",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Isca de tilápia",
      "slug": "isca-de-tilapia-g",
      "size": "G",
      "price": 19.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 14,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-015",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Calabresa acebolada",
      "slug": "calabresa-acebolada-g",
      "size": "G",
      "price": 19.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 15,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-016",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Filé de frango à milanesa",
      "slug": "file-de-frango-a-milanesa-g",
      "size": "G",
      "price": 19.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 16,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-017",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Linguiça toscana",
      "slug": "linguica-toscana-g",
      "size": "G",
      "price": 19.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 17,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-018",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Bisteca de porco",
      "slug": "bisteca-de-porco-g",
      "size": "G",
      "price": 19.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 18,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-019",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Carne de panela",
      "slug": "carne-de-panela-g",
      "size": "G",
      "price": 19.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 19,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-020",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Tilápia grelhada",
      "slug": "tilapia-grelhada-g",
      "size": "G",
      "price": 21.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 20,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-021",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Costelinha",
      "slug": "costelinha-g",
      "size": "G",
      "price": 24.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 21,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-022",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Filé de frango c/ creme de milho",
      "slug": "file-de-frango-creme-de-milho-g",
      "size": "G",
      "price": 29.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 22,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-023",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Carne seca acebolada",
      "slug": "carne-seca-acebolada-g",
      "size": "G",
      "price": 24.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 23,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-024",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Lasanha à bolonhesa",
      "slug": "lasanha-a-bolonhesa-g",
      "size": "G",
      "price": 24.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 24,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-025",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Bife acebolado",
      "slug": "bife-acebolado-g",
      "size": "G",
      "price": 25.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 25,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-026",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Bife empanado",
      "slug": "bife-empanado-g",
      "size": "G",
      "price": 27.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 26,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-027",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Bife a cavalo",
      "slug": "bife-a-cavalo-g",
      "size": "G",
      "price": 27.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 27,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-028",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Feijoada",
      "slug": "feijoada-g",
      "size": "G",
      "price": 29.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 28,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-029",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Nhoque recheado",
      "slug": "nhoque-recheado-g",
      "size": "G",
      "price": 29.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 29,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-030",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Parmegiana de berinjela",
      "slug": "parmegiana-de-berinjela-g",
      "size": "G",
      "price": 29.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 30,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-031",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Parmegiana de frango",
      "slug": "parmegiana-de-frango-g",
      "size": "G",
      "price": 29.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 31,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-032",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Parmegiana de tilápia",
      "slug": "parmegiana-de-tilapia-g",
      "size": "G",
      "price": 34.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 32,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-033",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Parmegiana de carne",
      "slug": "parmegiana-de-carne-g",
      "size": "G",
      "price": 34.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 33,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-034",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Parmegiana de truta",
      "slug": "parmegiana-de-truta-g",
      "size": "G",
      "price": 44.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 34,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-035",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Truta grelhada",
      "slug": "truta-grelhada-g",
      "size": "G",
      "price": 39.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 35,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-036",
      "category_id": "cat-marmitas",
      "category_slug": "marmitas",
      "name": "Salmão grelhado",
      "slug": "salmao-grelhado-g",
      "size": "G",
      "price": 44.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 36,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-037",
      "category_id": "cat-porcoes",
      "category_slug": "porcoes",
      "name": "Isca de tilápia 500gr",
      "slug": "isca-de-tilapia-500g",
      "size": null,
      "price": 55.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": true,
      "sort_order": 1,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-038",
      "category_id": "cat-porcoes",
      "category_slug": "porcoes",
      "name": "Isca de truta 400gr",
      "slug": "isca-de-truta-400g",
      "size": null,
      "price": 59.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 2,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-039",
      "category_id": "cat-porcoes",
      "category_slug": "porcoes",
      "name": "Camarão alho e óleo/empanado",
      "slug": "camarao-alho-oleo-empanado",
      "size": null,
      "price": 69.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 3,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-040",
      "category_id": "cat-porcoes",
      "category_slug": "porcoes",
      "name": "Mandioca 400gr",
      "slug": "mandioca-400g",
      "size": null,
      "price": 24.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 4,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-041",
      "category_id": "cat-porcoes",
      "category_slug": "porcoes",
      "name": "Batata frita simples 400gr",
      "slug": "batata-frita-simples-400g",
      "size": null,
      "price": 29.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 5,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-042",
      "category_id": "cat-porcoes",
      "category_slug": "porcoes",
      "name": "Batata frita cheddar e bacon 400gr",
      "slug": "batata-frita-cheddar-bacon-400g",
      "size": null,
      "price": 34.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 6,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-043",
      "category_id": "cat-porcoes",
      "category_slug": "porcoes",
      "name": "Carne seca acebolada 400gr",
      "slug": "carne-seca-acebolada-400g",
      "size": null,
      "price": 64.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 7,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-044",
      "category_id": "cat-porcoes",
      "category_slug": "porcoes",
      "name": "Contra filé acebolado 400gr",
      "slug": "contra-file-acebolado-400g",
      "size": null,
      "price": 64.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 8,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-045",
      "category_id": "cat-porcoes",
      "category_slug": "porcoes",
      "name": "Costelinha de porco 400gr",
      "slug": "costelinha-de-porco-400g",
      "size": null,
      "price": 49.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 9,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-046",
      "category_id": "cat-porcoes",
      "category_slug": "porcoes",
      "name": "Calabresa acebolada 400gr",
      "slug": "calabresa-acebolada-400g",
      "size": null,
      "price": 39.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 10,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-047",
      "category_id": "cat-porcoes",
      "category_slug": "porcoes",
      "name": "Calabresa acebolada e batata frita",
      "slug": "calabresa-acebolada-e-batata-frita",
      "size": null,
      "price": 39.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 11,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-048",
      "category_id": "cat-porcoes",
      "category_slug": "porcoes",
      "name": "Frango a passarinho",
      "slug": "frango-a-passarinho",
      "size": null,
      "price": 44.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 12,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-049",
      "category_id": "cat-porcoes",
      "category_slug": "porcoes",
      "name": "Kibe recheado",
      "slug": "kibe-recheado",
      "size": null,
      "price": 39.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 13,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-050",
      "category_id": "cat-porcoes",
      "category_slug": "porcoes",
      "name": "Salgado misto 25 un",
      "slug": "salgado-misto-25-un",
      "size": null,
      "price": 39.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 14,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-051",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Salmão grelhado",
      "slug": "salmao-grelhado",
      "size": null,
      "price": 44.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 1,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-052",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Truta grelhada",
      "slug": "truta-grelhada",
      "size": null,
      "price": 44.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 2,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-053",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Camarão empanado",
      "slug": "camarao-empanado",
      "size": null,
      "price": 44.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 3,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-054",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Bife a cavalo (ovo)",
      "slug": "bife-a-cavalo-ovo",
      "size": null,
      "price": 34.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 4,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-055",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Bife acebolado",
      "slug": "bife-acebolado",
      "size": null,
      "price": 34.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 5,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-056",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Feijoada",
      "slug": "feijoada",
      "size": null,
      "price": 34.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 6,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-057",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Carne de panela",
      "slug": "carne-de-panela",
      "size": null,
      "price": 29.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 7,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-058",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Strogonoff de frango",
      "slug": "strogonoff-de-frango",
      "size": null,
      "price": 29.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 8,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-059",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Strogonoff de carne",
      "slug": "strogonoff-de-carne",
      "size": null,
      "price": 34.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 9,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-060",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Arroz carreteiro",
      "slug": "arroz-carreteiro",
      "size": null,
      "price": 34.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 10,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-061",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Carne seca acebolada",
      "slug": "carne-seca-acebolada",
      "size": null,
      "price": 34.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 11,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-062",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Costelinha de tambaqui",
      "slug": "costelinha-de-tambaqui",
      "size": null,
      "price": 34.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 12,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-063",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Costelinha de porco",
      "slug": "costelinha-de-porco",
      "size": null,
      "price": 29.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 13,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-064",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Tilápia empanada isca",
      "slug": "tilapia-empanada-isca",
      "size": null,
      "price": 34.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 14,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-065",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Tilápia grelhada",
      "slug": "tilapia-grelhada",
      "size": null,
      "price": 29.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 15,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-066",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Bisteca",
      "slug": "bisteca",
      "size": null,
      "price": 24.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 16,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-067",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Linguiça Toscana",
      "slug": "linguica-toscana",
      "size": null,
      "price": 24.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 17,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-068",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Calabresa acebolada",
      "slug": "calabresa-acebolada",
      "size": null,
      "price": 24.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 18,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-069",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Frango empanado c/ creme de milho",
      "slug": "frango-empanado-creme-de-milho",
      "size": null,
      "price": 34.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 19,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-070",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Frango empanado",
      "slug": "frango-empanado",
      "size": null,
      "price": 24.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 20,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-071",
      "category_id": "cat-executivos",
      "category_slug": "pratos-executivos",
      "name": "Frango grelhado",
      "slug": "frango-grelhado",
      "size": null,
      "price": 24.99,
      "description": "Acompanha arroz, feijão, fritas e farofa.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 21,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-072",
      "category_id": "cat-especiais",
      "category_slug": "pratos-especiais",
      "name": "Parmegiana de carne",
      "slug": "parmegiana-de-carne",
      "size": null,
      "price": 39.99,
      "description": "Acompanha arroz e fritas.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 1,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-073",
      "category_id": "cat-especiais",
      "category_slug": "pratos-especiais",
      "name": "Parmegiana de tilápia",
      "slug": "parmegiana-de-tilapia",
      "size": null,
      "price": 39.99,
      "description": "Acompanha arroz e fritas.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 2,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-074",
      "category_id": "cat-especiais",
      "category_slug": "pratos-especiais",
      "name": "Parmegiana de frango",
      "slug": "parmegiana-de-frango",
      "size": null,
      "price": 34.99,
      "description": "Acompanha arroz e fritas.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": true,
      "sort_order": 3,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-075",
      "category_id": "cat-especiais",
      "category_slug": "pratos-especiais",
      "name": "Parmegiana de berinjela",
      "slug": "parmegiana-de-berinjela",
      "size": null,
      "price": 29.99,
      "description": "Acompanha arroz e fritas.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 4,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-076",
      "category_id": "cat-especiais",
      "category_slug": "pratos-especiais",
      "name": "Strogonoff de camarão",
      "slug": "strogonoff-de-camarao",
      "size": null,
      "price": 44.99,
      "description": "Acompanha arroz e fritas.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 5,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-077",
      "category_id": "cat-massas",
      "category_slug": "massas",
      "name": "Nhoque recheado",
      "slug": "nhoque-recheado",
      "size": null,
      "price": 39.99,
      "description": "Acompanha arroz e fritas.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 1,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-078",
      "category_id": "cat-massas",
      "category_slug": "massas",
      "name": "Lasanha",
      "slug": "lasanha",
      "size": null,
      "price": 39.99,
      "description": "Acompanha arroz e fritas.",
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 2,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-079",
      "category_id": "cat-refrigerantes",
      "category_slug": "refrigerantes",
      "name": "Latas",
      "slug": "latas",
      "size": null,
      "price": 8.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 1,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-080",
      "category_id": "cat-refrigerantes",
      "category_slug": "refrigerantes",
      "name": "H2O",
      "slug": "h2o",
      "size": null,
      "price": 9.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 2,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-081",
      "category_id": "cat-refrigerantes",
      "category_slug": "refrigerantes",
      "name": "Coca-Cola 1L",
      "slug": "coca-cola-1l",
      "size": null,
      "price": 14.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": true,
      "sort_order": 3,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-082",
      "category_id": "cat-refrigerantes",
      "category_slug": "refrigerantes",
      "name": "Tubaína 600ml",
      "slug": "tubaina-600ml",
      "size": null,
      "price": 10.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 4,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-083",
      "category_id": "cat-refrigerantes",
      "category_slug": "refrigerantes",
      "name": "Guaraná Piracaia 2L",
      "slug": "guarana-piracaia-2l",
      "size": null,
      "price": 10.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 5,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-084",
      "category_id": "cat-refrigerantes",
      "category_slug": "refrigerantes",
      "name": "Água com gás",
      "slug": "agua-com-gas",
      "size": null,
      "price": 5.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 6,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-085",
      "category_id": "cat-refrigerantes",
      "category_slug": "refrigerantes",
      "name": "Água",
      "slug": "agua",
      "size": null,
      "price": 4.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 7,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-086",
      "category_id": "cat-sucos",
      "category_slug": "sucos",
      "name": "Laranja / Maracujá",
      "slug": "laranja-maracuja",
      "size": null,
      "price": 14.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 1,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-087",
      "category_id": "cat-sucos",
      "category_slug": "sucos",
      "name": "Morango, abacaxi, manga, abacaxi c/ hortelã",
      "slug": "sabores-12",
      "size": null,
      "price": 12.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 2,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-088",
      "category_id": "cat-sucos",
      "category_slug": "sucos",
      "name": "Dois sabores",
      "slug": "dois-sabores",
      "size": null,
      "price": 16.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 3,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-089",
      "category_id": "cat-cervejas",
      "category_slug": "cervejas",
      "name": "Heineken",
      "slug": "heineken",
      "size": null,
      "price": 19.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 1,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-090",
      "category_id": "cat-cervejas",
      "category_slug": "cervejas",
      "name": "Original",
      "slug": "original",
      "size": null,
      "price": 17.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 2,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-091",
      "category_id": "cat-cervejas",
      "category_slug": "cervejas",
      "name": "Antártica",
      "slug": "antartica",
      "size": null,
      "price": 11.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 3,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-092",
      "category_id": "cat-cervejas",
      "category_slug": "cervejas",
      "name": "Skol",
      "slug": "skol",
      "size": null,
      "price": 11.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 4,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-093",
      "category_id": "cat-cervejas",
      "category_slug": "cervejas",
      "name": "Brahma",
      "slug": "brahma",
      "size": null,
      "price": 11.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 5,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-094",
      "category_id": "cat-cervejas",
      "category_slug": "cervejas",
      "name": "Heineken long neck",
      "slug": "heineken-long-neck",
      "size": null,
      "price": 11.99,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 6,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-095",
      "category_id": "cat-alcool",
      "category_slug": "bebidas-alcoolicas",
      "name": "Campari dose",
      "slug": "campari-dose",
      "size": null,
      "price": 15.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 1,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-096",
      "category_id": "cat-alcool",
      "category_slug": "bebidas-alcoolicas",
      "name": "Cachaça dose",
      "slug": "cachaca-dose",
      "size": null,
      "price": 8.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 2,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-097",
      "category_id": "cat-alcool",
      "category_slug": "bebidas-alcoolicas",
      "name": "Caipirinhas (morango, maracujá, limão, abacaxi)",
      "slug": "caipirinhas",
      "size": null,
      "price": null,
      "description": "Preço não informado no arquivo.",
      "image_path": null,
      "active": false,
      "available": true,
      "featured": false,
      "sort_order": 3,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-098",
      "category_id": "cat-alcool",
      "category_slug": "bebidas-alcoolicas",
      "name": "Sake",
      "slug": "sake",
      "size": null,
      "price": 20.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 4,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-099",
      "category_id": "cat-alcool",
      "category_slug": "bebidas-alcoolicas",
      "name": "Vodka",
      "slug": "vodka",
      "size": null,
      "price": 20.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 5,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-100",
      "category_id": "cat-alcool",
      "category_slug": "bebidas-alcoolicas",
      "name": "Velho Barreiro",
      "slug": "velho-barreiro",
      "size": null,
      "price": 18.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 6,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-101",
      "category_id": "cat-alcool",
      "category_slug": "bebidas-alcoolicas",
      "name": "Vinho garrafa",
      "slug": "vinho-garrafa",
      "size": null,
      "price": 25.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 7,
      "allow_notes": true,
      "notes_max_length": null
    },
    {
      "id": "prod-102",
      "category_id": "cat-alcool",
      "category_slug": "bebidas-alcoolicas",
      "name": "Vinho taça",
      "slug": "vinho-taca",
      "size": null,
      "price": 12.0,
      "description": null,
      "image_path": null,
      "active": true,
      "available": true,
      "featured": false,
      "sort_order": 8,
      "allow_notes": true,
      "notes_max_length": null
    }
  ],
  "daily_specials": [
    {
      "id": "special-demo",
      "weekday": 0,
      "product_id": "prod-074",
      "special_price": 32.99,
      "note": "Sugestão da casa",
      "active": true
    }
  ],
  "product_option_groups": [
    {
      "id": "grp-tilapia",
      "product_id": "prod-037",
      "code": "adicionais",
      "name": "Adicionais",
      "selection_type": "multiple",
      "required": false,
      "min_selections": null,
      "max_selections": null,
      "sort_order": 1,
      "active": true
    },
    {
      "id": "grp-bisteca-p",
      "product_id": "prod-006",
      "code": "adicionais",
      "name": "Adicionais",
      "selection_type": "multiple",
      "required": false,
      "min_selections": null,
      "max_selections": null,
      "sort_order": 1,
      "active": true
    },
    {
      "id": "grp-bisteca-g",
      "product_id": "prod-018",
      "code": "adicionais",
      "name": "Adicionais",
      "selection_type": "multiple",
      "required": false,
      "min_selections": null,
      "max_selections": null,
      "sort_order": 1,
      "active": true
    },
    {
      "id": "grp-latas",
      "product_id": "prod-079",
      "code": "escolha-sua-bebida",
      "name": "Escolha sua bebida",
      "selection_type": "single",
      "required": true,
      "min_selections": 1,
      "max_selections": 1,
      "sort_order": 1,
      "active": true
    }
  ],
  "product_options": [
    {
      "id": "grp-tilapia-o1",
      "group_id": "grp-tilapia",
      "code": "nenhum",
      "name": "Nenhum",
      "price_mode": "add",
      "price_value": 0,
      "is_none_option": true,
      "sort_order": 1,
      "active": true
    },
    {
      "id": "grp-tilapia-o2",
      "group_id": "grp-tilapia",
      "code": "porcao-arroz",
      "name": "Porção de arroz",
      "price_mode": "add",
      "price_value": 10,
      "is_none_option": false,
      "sort_order": 2,
      "active": true
    },
    {
      "id": "grp-tilapia-o3",
      "group_id": "grp-tilapia",
      "code": "porcao-feijao",
      "name": "Porção de feijão",
      "price_mode": "add",
      "price_value": 10,
      "is_none_option": false,
      "sort_order": 3,
      "active": true
    },
    {
      "id": "grp-bisteca-p-o1",
      "group_id": "grp-bisteca-p",
      "code": "acebolada",
      "name": "Acebolada",
      "price_mode": "add",
      "price_value": 0,
      "is_none_option": false,
      "sort_order": 1,
      "active": true
    },
    {
      "id": "grp-bisteca-p-o2",
      "group_id": "grp-bisteca-p",
      "code": "ovo-frito",
      "name": "Ovo frito",
      "price_mode": "add",
      "price_value": 3,
      "is_none_option": false,
      "sort_order": 2,
      "active": true
    },
    {
      "id": "grp-bisteca-g-o1",
      "group_id": "grp-bisteca-g",
      "code": "acebolada",
      "name": "Acebolada",
      "price_mode": "add",
      "price_value": 0,
      "is_none_option": false,
      "sort_order": 1,
      "active": true
    },
    {
      "id": "grp-bisteca-g-o2",
      "group_id": "grp-bisteca-g",
      "code": "ovo-frito",
      "name": "Ovo frito",
      "price_mode": "add",
      "price_value": 3,
      "is_none_option": false,
      "sort_order": 2,
      "active": true
    },
    {
      "id": "grp-latas-o1",
      "group_id": "grp-latas",
      "code": "coca-cola",
      "name": "Coca-Cola",
      "price_mode": "set",
      "price_value": 8,
      "is_none_option": false,
      "sort_order": 1,
      "active": true
    },
    {
      "id": "grp-latas-o2",
      "group_id": "grp-latas",
      "code": "coca-cola-zero",
      "name": "Coca-Cola Zero",
      "price_mode": "set",
      "price_value": 8,
      "is_none_option": false,
      "sort_order": 2,
      "active": true
    },
    {
      "id": "grp-latas-o3",
      "group_id": "grp-latas",
      "code": "guarana",
      "name": "Guaraná",
      "price_mode": "set",
      "price_value": 8,
      "is_none_option": false,
      "sort_order": 3,
      "active": true
    },
    {
      "id": "grp-latas-o4",
      "group_id": "grp-latas",
      "code": "suco-laranja",
      "name": "Suco de laranja",
      "price_mode": "set",
      "price_value": 12,
      "is_none_option": false,
      "sort_order": 4,
      "active": true
    }
  ]
};
